CREATE TABLE users (
    id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    login VARCHAR(30) NOT NULL,
    password VARCHAR(100) NOT NULL,
    email VARCHAR(50) NOT NULL,
    username VARCHAR(50) NOT NULL,
    surname VARCHAR(50) NOT NULL
);

CREATE TABLE roles (
    id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE user_roles (
    user_id INTEGER NOT NULL,
    role_id INTEGER NOT NULL,

    FOREIGN KEY (user_id) references users(id),
    FOREIGN KEY (role_id) references roles(id)
);

INSERT INTO users(id, login, password, email, username, surname)
        VALUES (1, 'murat1998', 'mura', 'mura@yandex.ru', 'Мурат', 'Азгарович');

INSERT INTO roles(id, name) VALUES (1, 'USER');
INSERT INTO roles(id, name) VALUES (2, 'ADMIN');

INSERT INTO user_roles(user_id, role_id) VALUES (1, 2);

DROP TABLE users;
DROP TABLE roles;
DROP TABLE user_roles;