CREATE TABLE users (
    id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uuid UUID NOT NULL,
    login VARCHAR(30) NOT NULL,
    password VARCHAR(100) NOT NULL,
    email VARCHAR(50) NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    surname VARCHAR(50) NOT NULL
);

INSERT INTO users(uuid, id, login, password, email, first_name, surname)
        VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 2, 'testLogin', 'testPassword', 'test@email.ru', 'testFirstName', 'testSurname');

DROP TABLE users;

SELECT * from users;
